spring:
  application:
    name: app

  datasource:
    url: jdbc:mysql://localhost:3306/spring?useSSL=false&serverTimezone=UTC
    username: spring
    password: 1234

mybatis:
  config-location: classpath:/config/config.xml
  mapper-locations: classpath*:/mapper/*.xml

server:
  port: 10000